### ISSUE TITLE
Интерфейс X2 / Signature is incorrect / Step=6

### ISSUE THREAD

**Issue by CheckThis0ut** [baibaratsky/php-webmoney#100]
Здравствуйте, работа с интерфейсом X2 работает с попеременным успехом: иногда всё отрабатывает корректно, а иногда валится ошибка:
http://img.netpeak.ua/chinaski/2016-08-12_74c912.jpg

Как вы видите, комментарии есть как на латинице, так и на кириллице. Никак не могу найти причину бага, гуглил - везде у всех ошибки step=5, а у меня еще и step=6. Можете помочь? Заранее спасибо!

**Comment by kotchuprik** [comment]
Если работает и не работает, но код не менялся, то проблема не в библиотеке, а в вебмани. То есть в первую очередь стоило написать в саппорт. Вы это сделали?

В ответе какой код выполнения запроса? -14?

**Comment by CheckThis0ut** [comment]
> Если работает и не работает, но код не менялся, то проблема не в библиотеке, а в вебмани. 
Я думал, может что с кодировкой или какие-то знаки нельзя писать в описании, что-то в таком духе.

>  Вы это сделали?
Да, жду ответа. Но я слабо верю, что они могут как-то помочь, у них же ровное API, я надеюсь))

> В ответе какой код выполнения запроса? -14?
Да.

**Comment by kotchuprik** [comment]
То есть с латинским описанием транзакции без # и прочих символов транзакции проходят?

**Comment by CheckThis0ut** [comment]
Тут сплошной рандом, иногда и латиница не проходит. Бывает даже так: создаём транзакцию - валится ошибка, через время создаем еще раз (все данные те же самые) - уже всё норм.

**Comment by kotchuprik** [comment]
И еще раз вижу подтверждение, что апи бажит :) Тогда предлагаю ждать ответа саппорт и тогда уже как-то пытаться решить проблему. В данный момент бага звучит как поиск иглы в стоге сена, библиотека сейчас используется в проде и проблем с Х2 нет.

**Comment by baibaratsky** [comment]
> Да, жду ответа. Но я слабо верю, что они могут как-то помочь, у них же ровное API, я надеюсь))

Зря надеетесь 😉
