### ISSUE TITLE
Проблемы с SSL в CurlRequester.

### ISSUE THREAD

**Issue by stas17** [baibaratsky/php-webmoney#102]
#90 
Снова здравствуйте. 
При установке версии ssl = 1 
`curl_setopt($handler, CURLOPT_SSLVERSION, 1);`
получаю
**Error while performing request (Unknown SSL protocol error in connection to w3s.webmoney.ru:443 )**

При установке версии ssl = 4 все гуд (версии 2 и 3 не безопасны)

Есть у меня мнение, что я что то не так делаю с версией 1, но получилось поправить только сменой  версии.

Может быть добавить метод setSSLVersion в CurlRequester?
 `
$xmlRequester new CurlRequester(); `
`
$xmlRequester->setSSLVersion(CURL_SSLVERSION_TLSv1_0);
`
А в  CurlRequester
`class CurlRequester extends AbstractRequester`
`{`
`     private $sslVersion = CURL_SSLVERSION_TLSv1;`
Спс. 

P.S.
Ну, и немного занудства. Мне больше нравится использование стандартных констант 
**CURL_SSLVERSION_TLSv1** для v1,
**CURL_SSLVERSION_TLSv1_0** для v4.

**Comment by kotchuprik** [comment]
привет,

> Есть у меня мнение, что я что то не так делаю с версией 1, но получилось поправить только сменой версии.

у вебмани был прикол, что на одном из роутов другая версия ssl только работала, сейчас не смогу сказать в каком

> Может быть добавить метод setSSLVersion в CurlRequester?

да, неплохая идея. @baibaratsky, что скажешь?

> Ну, и немного занудства. Мне больше нравится использование стандартных констант 

может быть pull request? :)

**Comment by stas17** [comment]
> может быть pull request? :)

CURL_SSLVERSION_TLSv1_0 (integer)
Доступна начиная с версий PHP 5.5.19 и 5.6.3
CURL_SSLVERSION_TLSv1_1 (integer)
Доступна начиная с версий PHP 5.5.19 и 5.6.3
CURL_SSLVERSION_TLSv1_2 (integer)
Доступна начиная с версий PHP 5.5.19 и 5.6.3

учитывать совместимость с php version < 5.5.19?

**Comment by kotchuprik** [comment]
О, это очень крутой вопрос. У нас совместимость 5.3 и выше. Поэтому, пройдем мимо системных констант ))

**Comment by stas17** [comment]
remote: Permission to baibaratsky/php-webmoney.git denied to stas17.
fatal: unable to access 'https://github.com/baibaratsky/php-webmoney.git/': The requested URL returned error: 403

**Comment by kotchuprik** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by baibaratsky** [comment]
@stas17 На каких интерфейсах наблюдаете проблему? Есть у меня подозрение, что разные интерфейсы ведут себя по-разному.

**Comment by stas17** [comment]
@baibaratsky  x2

**Comment by stas17** [comment]
https://github.com/baibaratsky/php-webmoney/pull/103
добавил метод
есть еще идея с отловом ошибки и повторным запросом с другой версией ssl

**Comment by baibaratsky** [comment]
@stas17 Попробуйте, пожалуйста, X3 с версиями 1 и 4.

Не уверен, что нужен такой метод, если мы найдем версию, которая будет работать для всех.

**Comment by stas17** [comment]
для x3 история повторяется
ssl v1 - ошибка
ssl v4 - работает

**Comment by stas17** [comment]
поднимаю тему. 
Всем привет.

**Comment by baibaratsky** [comment]
Прошу прощения. Свободного времени очень мало.

**Comment by baibaratsky** [comment]
Спасибо за ваш вклад!

**Comment by stas17** [comment]
Спасибо за оперативную реакцию.
