### ISSUE TITLE
Работа с сертификатом от Keeper Lite

### ISSUE THREAD

**Issue by ange007** [baibaratsky/php-webmoney#104]
По какой-то причине не выходит работать с сертификатом **Keeper Light**.
Выпадаёт ошибка:  `PHP Fatal error:  Call to undefined method baibaratsky\\WebMoney\\Api\\X\\X3\\Request::lightAuth() in *`

Собственно код: 
```php 
<?php
namespace pay\modules;

use baibaratsky\WebMoney\WebMoney;
use baibaratsky\WebMoney\Api\X\X2;
use baibaratsky\WebMoney\Api\X\X3;
use baibaratsky\WebMoney\Request\Requester\CurlRequester;
	
// Дополнительный функционал ручного метода оплаты
class pm_webmoney extends manualModule  
{
	private $wmid = '*';
	private $certificateKey = '/*.spc';
	private $certificateFile = '/*.p12';
	private $fileKeyPassword = '*';

	//
	public function __construct( )
	{

	}

	// Проверка состояния оплаты
	public function checkPayments( $orderID, $amount, $currency )
	{	
		//
		$webMoney = new WebMoney( new CurlRequester );

		// Формируем запрос
		$request = new X3\Request( X3\Request::AUTH_LIGHT );
		// $request->setRequestedWmid( $this->wmid );
		$request->setPurse( * );
		$request->setStartDateTime( new \DateTime( '-1 week' ) );
		$request->setEndDateTime( new \DateTime );

		// Подписываем запрос
		$request->lightAuth( $this->certificateFile, $this->certificateKey, $this->fileKeyPassword );
....
```
В чём может быть причина такого поведения?

**Comment by kotchuprik** [comment]
1) Версия последняя установлена?
2) В файле `php-webmoney/Api/X/Request.php` lightAuth есть?
3) `var_export($request)` что дает?

**Comment by ange007** [comment]
> 1) Версия последняя установлена?
2) В файле php-webmoney/Api/X/Request.php lightAuth есть?
3) var_export($request) что дает?

Прошу прощения, версия была не новая _(зависимость ставил по данным из Readme)_.

**З.Ы.** Кстати в Readme не плохо было-бы добавить информацию как делать сертификаты от Light в правильном формате _(а то даже не понятно какие именно файлы должны быть)_. Пол дня мозги ломал.

**Comment by kotchuprik** [comment]
А либа разве является мануалом по пользованию вебмани?)

**Comment by ange007** [comment]
>А либа разве является мануалом по пользованию вебмани?)

Нет, но я например не нашёл в мануалах какие именно файлы нужны.
А так для тех кто юзает либу - это важно, и избавило бы от многих вопросов _( достаточно ведь указать расширения файлов даже)_.

**Comment by kotchuprik** [comment]
Репозиторий всегда открыт к пулл реквестам :)
Если есть желание, то создайте ишью со ссылкой на мануал и его добавим в WIKI

**Comment by ange007** [comment]
Пришлось обновлять сертификат и снова искал информацию.

Возможно кому поможет: https://wiki.webmoney.ru/projects/webmoney/wiki/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F_%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B9_WM_Keeper_WebPro_%D0%B2_PEM-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82
