### ISSUE TITLE
Проблемы с авторизацией AUTH_LIGHT

### ISSUE THREAD

**Issue by mastermind-ua** [baibaratsky/php-webmoney#109]
Возникли проблемы с использованием интерфейса X4. Запрос следующего вида:
```
<w3s.request>
   <reqn>148400317916191</reqn>
   <getoutinvoices>
      <purse>R*********</purse>
      <wminvid>123456789</wminvid>
      <datestart>20170110 00:48:06</datestart>
      <datefinish>20170110 00:48:06</datefinish>
   </getoutinvoices>
</w3s.request>
```

Ответ:
```
<?xml version="1.0"?>
<w3s.response>
     <reqn>148400317916191</reqn>
      <retval>-1</retval>
      <retdesc>wrong wmid of signer step=3</retdesc>
</w3s.response>
```

Решение проблемы:
[https://wiki.webmoney.ru/projects/webmoney/wiki/%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81_X4](url)

> URL для передачи запроса с авторизацией по ключам WM Keeper WebPro (Light) - https://w3s.wmtransfer.com/asp/XMLOutInvoicesCert.asp

При этом в коде запросы идут на другой домен
> WebMoney\Api\X\X4\Request.php
> https://w3s.wmtransfer.com/asp/XMLOutInvoicesCert.asp

Аналогичная ситуация, судя по всему, и по другим интерфейсам. Но они почему-то работают.

**Comment by kotchuprik** [comment]
Я верно понимаю, что вы используете Light авторизацию? Остальные интерфейсы точно не работают? Например X11

**Comment by mastermind-ua** [comment]
Да, авторизация Light. X11 проверить возможности нет, к сожалению. X1, X2, X9 работают, но там урлы правильные. X4 заработал только после замены урла на тот, который в доке.

**Comment by kotchuprik** [comment]
Давай пулл реквест и смержим завтра :) Возможно, X4 просто не тестировали на лайте, мы классик юзаем в основном.

**Comment by mastermind-ua** [comment]
Этот интерфейс я проверял на новом урле. Там еще два осталось, X15 и X19.
