### ISSUE TITLE
x19

### ISSUE THREAD

**Issue by sergek99** [baibaratsky/php-webmoney#111]
для работы с x19 обязательно нужен kwm файл или достаточно light_auth (key, cer, pass)

**Comment by baibaratsky** [comment]
Можно light

**Comment by sergek99** [comment]
а как подписать через light?

**Comment by baibaratsky** [comment]
https://github.com/baibaratsky/php-webmoney#authentication-with-a-light-certificate

**Comment by sergek99** [comment]
но это только x9
а в x19 это не работает

**Comment by baibaratsky** [comment]
Для X19 все так же. Прежде, чем делать подобные заявления, неплохо бы приложить доказательство в виде неработающего кода. Желательно с анализом и выводами, почему он не работает.
Вы пока первый, у кого не работает, так что я склонен считать, что проблема в вашем коде.
Тот код, который вы мне присылали по email не будет работать. Я вам написал, почему.

**Comment by sergek99** [comment]
параметр passport.request/sign про который я написал - это и есть подпись запроса
[sign	подпись запроса	обязательный параметр, формируется из параметров: //reqn + //operation/type + //userinfo/wmid; используется только при авторизации с ключами WM Keeper WinPro (Classic) ](http://wiki.webmoney.ru/projects/webmoney/wiki/%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81_X19)

он добавляется только через 
$request->sign(new Signer('YOUR WMID', 'FULL PATH TO KEY FILE', 'KEY FILE PASSWORD'));
где FULL PATH TO KEY FILE - file.kwm

**Comment by sergek99** [comment]
и значит что без kwm x19 бесполезен

**Comment by baibaratsky** [comment]
Все верно. Если вы отправляете запрос на XMLCheckUser.aspx, этот параметр обязателен. Чтобы отправлять на XMLCheckUserCert.aspx, нужно правильно создавать запрос:
```php
$request = new Request(Request::AUTH_LIGHT);
```

**Comment by sergek99** [comment]
Fatal error: Uncaught baibaratsky\WebMoney\Exception\RequesterException: Error while performing request (could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?)) in /Users/sketcompani/Work/Projects/ultragold/ultragold.org/web/vendor/baibaratsky/php-webmoney/Request/Requester/CurlRequester.php on line 67
( ! ) baibaratsky\WebMoney\Exception\RequesterException: Error while performing request (could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?)) in /Users/sketcompani/Work/Projects/ultragold/ultragold.org/web/vendor/baibaratsky/php-webmoney/Request/Requester/CurlRequester.php on line 67

**Comment by sergek99** [comment]
я это получаю если использую $request = new Request(Request::AUTH_LIGHT);

**Comment by baibaratsky** [comment]
> could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?)

**Comment by sergek99** [comment]
ну а где указать этот pem файл?

**Comment by sergek99** [comment]
в папке с ключами он у меня есть
