### ISSUE TITLE
confused on parameters

### ISSUE THREAD

**Issue by sahidul99** [baibaratsky/php-webmoney#124]
$request->setSignerWmid('YOUR WMID');
$request->setRequestedWmid('REQUESTED WMID');

Here what is 'Your WMID' and 'REQUESTED WMID'
I should have only one WMID

**Comment by baibaratsky** [comment]
https://wiki.wmtransfer.com/projects/webmoney/wiki/Interface_X9

You can request information about another WMID. This WMID called “requested” here.

**Comment by sahidul99** [comment]
I want to get my purse balance, I tried by set both same wmid, that output
error step 13,
I tried with 2 different wmid, (both is mine), same response.
 I have tried by comment out and keep empty on requested wmid, both does
not print anything.
