### ISSUE TITLE
Возвращает ложно-положительное значение в некоторых случаях.

### ISSUE THREAD

**Issue by davemodis** [baibaratsky/php-webmoney#126]
https://github.com/baibaratsky/php-webmoney/blob/12434d508d43bbc9f41f97da57d5173e5342d367/Api/X/X8/Response.php#L40

Решение: Операция должна быть побитовое И (&), а не сравнение (>=).

**Comment by DKudleichuk** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

vwcsm, @longbow1998, @davehorner, @nagas, @shunkakinoki, @zzzihao-li, @binocarlos, @micici, @vinniejames, @Debaba13, @femialex, @zlexdl, @0xtaosu, @XatMassacrE, @cagodoy, @carterax, @MZ1387, @fxsjy, @LinAsan-1205, @ebk13579
