### ISSUE TITLE
X9 - 403 - Forbidden: Access is denied. 

### ISSUE THREAD

**Issue by allfreelancers** [baibaratsky/php-webmoney#127]
403 - Forbidden: Access is denied.
You do not have permission to view this directory or page using the credentials that you supplied.

```
echo $response->getRawData();
```

почему? в чем может быть проблема?

**Comment by allfreelancers** [comment]
@baibaratsky есть мысли?

**Comment by baibaratsky** [comment]
@allfreelancers, нет. Я уже несколько лет не работаю с API WebMoney, так что не могу ничего по нему подсказать.
