### ISSUE TITLE
Couldn't request interface_x9

### ISSUE THREAD

**Issue by ebrahimsalahi** [baibaratsky/php-webmoney#128]
require_once(__DIR__ . '/vendor/autoload.php'); // Require autoload file generated by composer

use baibaratsky\WebMoney;
use baibaratsky\WebMoney\Signer;

$webMoney = new WebMoney\WebMoney(new WebMoney\Request\Requester\CurlRequester);

$request = new WebMoney\Api\X\X9\Request;
$request->setSignerWmid('522-----7401');
$request->setRequestedWmid('522*****7401');

$request->sign(new Signer('522-----7401',__DIR__ . '522-----7401.kwm', '*******'));

if ($request->validate()) {
    $response = $webMoney->request($request);

    if ($response->getReturnCode() === 0) {
        echo  $response->getPurseByName('Z64-----30013')->getAmount();
    } else {
        echo 'Error: ' . $response->getReturnDescription();
    }

}

result : 

```

string(163) "<?xml version="1.0"?>
<w3s.response>
<reqn>160546003307119</reqn>
<retval>110</retval>
<retdesc>Server Error step=13</retdesc>
<ser>Srv10</ser>
</w3s.response>"

  Error: Server Error step=13

```

**Comment by ebrahimsalahi** [comment]
@baibaratsky please help

**Comment by baibaratsky** [comment]
Can’t help, sorry. Try to ask WebMoney support.
