### ISSUE TITLE
Add the php-webmoney dependency error

### ISSUE THREAD

**Issue by luyenok** [baibaratsky/php-webmoney#63]
I got error when Adding the php-webmoney dependency:

root@do [/home/the247/public_html/wmzapi]# php composer.phar require baibaratsky/php-webmoney:0.10.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package baibaratsky/php-webmoney 1.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
root@do [/home/the247/public_html/wmzapi]#

**Comment by baibaratsky** [comment]
Could you show your composer.json?

**Comment by luyenok** [comment]
{
    "name": "baibaratsky/php-webmoney",
    "description": "WebMoney API PHP Library",
    "keywords": ["webmoney", "megastock", "capitaller", "WMXI", "WMSigner"],
    "license": "BSD-3-Clause",
    "homepage": "http://github.com/baibaratsky/php-webmoney",
    "authors": [
        {
            "name": "Andrei Baibaratsky",
            "email": "andrei@baibaratsky.com"
        },
        {
            "name": "Constantin Chuprik",
            "email": "constantinchuprik@gmail.com"
        }
    ],
    "require": {
        "php": ">=5.3",
        "baibaratsky/php-wmsigner": "1.1.*"
    },
    "autoload": {
        "psr-4": {
            "baibaratsky\\WebMoney\\": ""
        }
    }
}

**Comment by luyenok** [comment]
I just downloaded and uploaded to my server, did not change anythings.

**Comment by baibaratsky** [comment]
It's my composer.json. Please show me one from your project root directory.

**Comment by luyenok** [comment]
sorry, I have not anything, I justed downloaed php-webmoney-master.zip file and uploaded to my server :(

**Comment by baibaratsky** [comment]
If you want to use Composer, you don’t have to upload any files from this repository. Please read [the Composer docs](https://getcomposer.org/doc/00-intro.md) to discover how to use it.

To use the library without Composer, add `require` calls for all the library files.

**Comment by luyenok** [comment]
thank you, I have added require calls for all the library files and tested X2 (transfer fund), I got the error: Request errors: - Array
I try to print_r ($request->getErrors()); and result is: Array ( [1] => Array ( [0] => transactionExternalId ) )

Can you help me ? I just want to using X2 to transfer fund to other purse.

**Comment by baibaratsky** [comment]
Could you attach your code please?

**Comment by luyenok** [comment]
yes, how to attach ? This form accept image file only.

**Comment by baibaratsky** [comment]
Just put your code in the message here. Please use [markdown](https://guides.github.com/features/mastering-markdown/) to highlight the code.

**Comment by luyenok** [comment]
<?
require_once('WebMoney.php');
require_once('Signer.php');
require_once('Request/Requester/CurlRequester.php');
require_once('Request/Requester/AbstractRequester.php');
require_once('Api/X/X2/Request.php');
require_once('Api/X/X2/Response.php');

use baibaratsky\WebMoney\WebMoney;
use baibaratsky\WebMoney\Signer;
use baibaratsky\WebMoney\Request\Requester\CurlRequester;
use baibaratsky\WebMoney\Api\X\X2;

$webMoney = new WebMoney(new CurlRequester);

$request = new X2\Request;
$request->setSignerWmid('removed');
$request->setPayerPurse('removed');
$request->setPayeePurse('removed');
$request->setAmount(0.01); // Payment amount
$request->setDescription('Test payment');
$request->setInvoiceId(0);

$request->sign(new Signer('removed', 'removed.kwm', 'removed'));

if ($request->validate()) {
    /** @var X2\Response $response */
    $response = $webMoney->request($request);

    if ($response->getReturnCode() === 0) {
        echo 'Successful payment, transaction id: ' . $response->getTransactionId();
    } else {
        echo 'Payment error: ' . $response->getReturnDescription();
    }
} else {
    echo 'Request errors: ' . PHP_EOL;
    print_r ($request->getErrors());
    foreach ($request->getErrors() as $error) {
        echo ' - ' . $error . PHP_EOL;
    }
}


?>

**Comment by luyenok** [comment]
the result is `Request errors: Array ( [1] => Array ( [0] => transactionExternalId ) ) - Array`

**Comment by luyenok** [comment]
you can download full code here http://muathe247.com/wmzapiok/testX2.zip

**Comment by baibaratsky** [comment]
You have to set a required parameter `transactionExternalId`. Put this string in your code:
```php
$request->setTransactionExternalId($myTransactionId); // Unique ID of the transaction in your system
```
`$myTransactionId` should be a positive integer, unique for the WMID that signs the request. It’s not allowed to perform two transactions with the same ID.

**Comment by luyenok** [comment]
thank you for your support, I got new error:
`Payment error: signature is incorrect. planstr=1427764213510054Z222213656185Z2820325325120.010Test payment0 step=5`

**Comment by baibaratsky** [comment]
Does `payerPurse` belong to `signerWmid`?

**Comment by luyenok** [comment]
yes, payerPurse belong to signerWmid, I have tested X9 and it working file (show Purse's balance), but got error with X2 :(

**Comment by baibaratsky** [comment]
There was a small bug with the signature in the X2 request class. Please update the library and try again.

**Comment by luyenok** [comment]
yahoooooooooooo !!!!!!!!!!!!!!!!!!
`Successful payment, transaction id: 1175379855`

thank you very much,

**Comment by baibaratsky** [comment]
You’re welcome!

**Comment by luyenok** [comment]
Hic, it working one time only, got bellow error when try agian
`Payment error: Out of present range. step=91`

**Comment by baibaratsky** [comment]
```php
    /**
     * Set ID of the transaction in your system
     *
     * @param int $transactionExternalId should be a positive integer, unique for the WMID that signs the request
     * It’s not allowed to perform two transactions with the same ID.
     * The uniqueness of ID is verified at least for one year.
     */
    public function setTransactionExternalId($transactionExternalId)
```

**Comment by luyenok** [comment]
what's your mean ?

**Comment by luyenok** [comment]
same problem here https://translate.google.com.vn/translate?hl=vi&sl=ru&tl=en&u=http%3A%2F%2Fcafe.owebmoney.ru%2Findex.php%3Fshowtopic%3D6206

it working if TransactionExternalId lenght <10 only, got error `Out of present range` if Out of present range lenght >10.

**Comment by baibaratsky** [comment]
I thought you use the same value for `transactionExternalId`.
So since `transactionExternalId` is a 32-bit integer, you shouldn’t use values greater than `(2^32)-1`.
