### ISSUE TITLE
Ошибка подписи

### ISSUE THREAD

**Issue by mitalcoi** [baibaratsky/php-webmoney#66]
не получается использовать X2 - следующая ошибка: "signature is incorrect. planstr=<строка> step=5" Auth type у нас - classic, проблема именно в том как подпись формируется. на WMXI(библиотека, которую раньше использовали) все подписывалось нормально. при этом остальные интерфейсы (например X9) работают нормально.

**Comment by baibaratsky** [comment]
Покажите код

**Comment by mitalcoi** [comment]
```
class WmApi
{
    protected $wmid;
    protected $keyFileName;
    protected $keyPassword;
    protected $logger;

    /**
     * @param $wmid
     * @param $keyFileName
     * @param $keyPassword
     * @param LoggerInterface $logger
     */
    public function  __construct($wmid, $keyFileName, $keyPassword, LoggerInterface $logger)
    {
        $this->wmid = $wmid;
        $this->keyFileName = $keyFileName;
        $this->keyPassword = $keyPassword;
        $this->logger = $logger;
    }

    public function getWmid()
    {
        return $this->wmid;
    }

    protected function sign(AbstractRequest $request)
    {
        $request->sign(new Signer($this->wmid, $this->keyFileName, $this->keyPassword));
    }

    /**
     * @param $externalId
     * @param $pursesrc
     * @param $pursedest
     * @param $amount
     * @param $comment
     * @throws RequestValidatorException
     * @throws \baibaratsky\WebMoney\Exception\CoreException
     * @return X\X2\Response
     */
    public function X2($externalId, $pursesrc, $pursedest, $amount, $comment)
    {
        $request = new X\X2\Request(X\X2\Request::AUTH_CLASSIC);
        $request->setSignerWmid($this->getWmid());
        $request->setTransactionExternalId($externalId);
        $request->setPayerPurse($pursesrc);
        $request->setPayeePurse($pursedest);
        $request->setAmount($amount);
        $request->setDescription($comment);
        $request->setInvoiceId(0);
        $this->sign($request);
        if ($request->validate()) {
            $res = $this->getRequester()->request($request);
            if ($res->getReturnCode() !== 0) {
                $this->logger->warning("X2", [$res->getReturnDescription()]);
            }
        } else {
            $this->logger->alert("X2 is not valid", $request->getErrors());
            throw new RequestValidatorException;
        }
    }
}
```

**Comment by baibaratsky** [comment]
Попробуйте
```php
protected function sign(AbstractRequest &$request)
```

**Comment by mitalcoi** [comment]
у меня php 5.5, объекты по ссылке должны передаваться по умолчанию железно, разве нет?

**Comment by mitalcoi** [comment]
единственно в чем вижу разницу - protectionCode:null, в то время как в WMXI шла просто пустая строка  - "". Может из-за этого формироваться подпись неверная? Может сделать по умолчанию значение в protectionCode = ""?

**Comment by mitalcoi** [comment]
библиотека WMXI перед тем как отдать данные на подпись форсировано преобразует кодировку в windows-1251:
```php
	protected function _sign($text) {
		if (!$this->classic) { die('Classic initialization required to sign the string.'); }
		if (function_exists('mb_convert_encoding')) {
			$text = mb_convert_encoding($text, 'windows-1251', $this->encoding);
		} elseif (function_exists('iconv')) {
			$text = iconv($this->encoding, 'windows-1251', $text);
		}
		return $this->signer->Sign($text);
	}
```
Может ли это как-то влиять?

**Comment by baibaratsky** [comment]
У меня до 23 мая очень ограниченный доступ к интернету и мало свободного времени, поэтому, я надеюсь, что @kotchuprik вам поможет.

**Comment by kotchuprik** [comment]
Если WMXI под рукой, сможете показать примерные исходные строки для подписи?

Для php-webmoney сделать дамп этой конкатенации https://github.com/baibaratsky/php-webmoney/blob/master/Api/X/X2/Request.php#L121
Для WMXI https://github.com/frost-nzcr4/webmoney/blob/master/src/webmoney/WMXI.php#L56

Насчет WIN-1251 по идее проблем не должно быть, данная библиотека работает в нескольких проектах с переводами :) Но если у вас в описании платежа есть кириллица, то временно для теста сможете поменять на латинское описание?

**Comment by ilyenkoyaroslav** [comment]
Сталкнулся с такой же проблемой но с X3
Получаю ошибку такого вида:
baibaratsky\WebMoney\Api\X\X3\Response Object
(
    [requestNumber:protected] => 14317174575235
    [operations:protected] => Array
        (
        )

    [returnCode:protected] => -5
    [returnDescription:protected] => signature is incorrect. planstr=Z11303573606014517173575234 step=7
)

**Comment by kotchuprik** [comment]
@ilyenkoyaroslav покажите код)

**Comment by ilyenkoyaroslav** [comment]
```
$webmoney = new \baibaratsky\WebMoney\WebMoney(new \baibaratsky\WebMoney\Request\Requester\CurlRequester());

        $request = new \baibaratsky\WebMoney\Api\X\X3\Request;
        $request->setSignerWmid(Settings::$webmoney_config['WMID']);
        $request->setPurse(Settings::$webmoney_config['WMZ']);
        $request->setStartDateTime(new DateTime('-3 day'));
        $request->setEndDateTime(new DateTime('+1 day'));
        $request->sign(new \baibaratsky\WebMoney\Signer(Settings::$webmoney_config['WMID'], '/wm_certificate/' . Settings::$webmoney_config['certificate_name'], Settings::$webmoney_config['certificate_password']));

        if ($request->validate()) {
            $response = $webmoney->request($request);
        }
```

**Comment by kotchuprik** [comment]
Очень странно, а остальные интерфейсы корректно работают? С WMID все в порядке?

**Comment by ilyenkoyaroslav** [comment]
С WMID всё в порядке + на локальноя машине получаю все транзакции без проблем. До недавнего времени так же было и на хостинге. Файлы связанные с WM не менял.
Остальные интерфейсы сейчас к сожалению проверить не могу.

**Comment by ilyenkoyaroslav** [comment]
@kotchuprik У Вас нет идея почему может быть так?

**Comment by kotchuprik** [comment]
А сможете попробовать проверить работоспособность на релизе 0.10.1?

https://github.com/baibaratsky/php-webmoney/releases/tag/v0.10.1

**Comment by ilyenkoyaroslav** [comment]
@kotchuprik Если не ошибаюсь у меня как раз 0.10.1http://prntscr.com/75t1su

**Comment by kotchuprik** [comment]
Так, а получится попробовать свежую версию (0.10.3)?
Или есть возможность сверить работу с WMXI, то тоже было бы неплохо..
Потому что такая проблема вероятнее всего связана именно с webmoney (библиотека не менялась, у вас код не менялся, все по старому и внезапно перестало работать), но я не смог ничего найти кроме как подобных тем на форуме и проблем с WMID.

**Comment by mitalcoi** [comment]
на 0.10.3 тоже самое (X2 не работает) Комментарий пробовал делать латиницей - не помогло. А WMXI работает (как только откатились к WMXI - транзакции стали выполняться без ошибок). При этом X9 работает и там и там

**Comment by kotchuprik** [comment]
@mitalcoi получилось сделать итоговых строк для подписи? есть видимые различия?

**Comment by mitalcoi** [comment]
нет! там банальная конкатенация. Request number немного по-разному генерится, не знаю насколько это может иметь значение.
у вас:
```php
str_pad(str_replace('.', '', microtime(true)), 14, 0)
```
WMXI:
```php
list($usec, $sec) = explode(' ', substr(microtime(), 2));
		$this->lastreqn = ($this->reqn > 0) ? $this->reqn : substr($sec.$usec, 0, 15);
		return $this->lastreqn;
```

**Comment by kotchuprik** [comment]
То есть разница только в requestNumber?
Это не имеет значение, на самом деле. Главное, чтобы каждый следующий requestNumber был больше предыдущего.

**Comment by mitalcoi** [comment]
это да...но с другой стороны WM ведь опирается на requestNumber при сверке подписи. откуда он знает какое мы ему значение передали? если он раньше возрастал монотонно, а потом резко стал иметь другие значения?

**Comment by mitalcoi** [comment]
вот:
"reqn	 - целое без знака, макс. количество цифр - 15; всегда должен быть больше номера предыдущего запроса на перевод средств!!! Монотонность возрастания номера учитывается в привязке к WMID, подписывающему запрос." - https://wiki.webmoney.ru/projects/webmoney/wiki/%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81_X2

У меня, судя по всему, нарушилась монотонность нарастания reqn

**Comment by kotchuprik** [comment]
WM значет об requestNumber потому мы его передаем. А подпись это вычисление хэша. Насчет монотонности не встречал ранее. 

Задам вопрос еще раз — в итоговых строках разница только в requestNumber?

**Comment by mitalcoi** [comment]
да, разница только в requestNumber.

**Comment by kotchuprik** [comment]
Очень странно. Виктор, а в данный момент WMXI создает номер запроса больше, чем php-webmoney?

**Comment by baibaratsky** [comment]
Думаю, что проблема может быть в том, что ранее был передан больший requestNumber. У меня сразу эта мысль была, но отвлекся и не написал.

**Comment by mitalcoi** [comment]
Да. вот результат сравнения requestNumber
php-webmoney
14318306913668
WMXI
143183069136693
в Базовом Request-классе есть сеттер, так что не проблема - буду устанавливать reqn форсированно сам. Но я думаю в документации стоит оговорить об этой проблеме при переходе с WMXI на вашу библиотеку

**Comment by baibaratsky** [comment]
Хорошо. Спасибо, @kotchuprik

**Comment by kotchuprik** [comment]
Можно генератор requestNumber сделать как в WMXI по разрядности.

**Comment by mitalcoi** [comment]
кстати да, тоже вариант

**Comment by mitalcoi** [comment]
сделал форсированную установку сеттера, разрядность теперь совпадает - все равно выдает на боевом сервере ошибку:
"signature is incorrect. planstr=14319367646011647242<PURSE_1><PURSE_2>1.890<COMMENT> step=5"

**Comment by mitalcoi** [comment]
Путем экспериментов удалось выяснить что проблема возникает только если в комментарии к заявке идет кириллица

**Comment by kotchuprik** [comment]
А ведь про кириллицу спрашивал ранее))
Да, вероятнее всего надо все менять на mb_

**Comment by ilyenkoyaroslav** [comment]
@kotchuprik Свежие новости с фронтов) 
Не меняя ни строчки кода - X3 начал работать - начал грешить на блок от wm временный, но не могу понять, как это связано с сигнатурой?

**Comment by kotchuprik** [comment]
@ilyenkoyaroslav ни для кого ни секрет, что у WM все через одно место :smiley: Видимо у них подпись это серебряная пуля для ошибок.

**Comment by baibaratsky** [comment]
@mitalcoi @kotchuprik strlen в Signer используется для бинарных строк. Там в любом случае нужна длина в байтах, а не в символах.

**Comment by baibaratsky** [comment]
Если точнее, не только для них, еще для шестнадцатиричных чисел и пароля от ключа. В общем, это не может быть источником неприятностей.

**Comment by mitalcoi** [comment]
тем не менее, проблема в Signer, ей просто больше негде быть)
строка с кириллическими символами пробрасывается в Signer - и там с ними что-то плохое происходит

**Comment by baibaratsky** [comment]
У меня в нескольких проектах кириллические строки отлично подписываются. Нет никаких проблем. Думаю, дело все-таки в кодировке.
Какие кодировки у вашего кода, у строки, которая используется в комментарии, у запроса и ответа сервера (если присутствуют)?

**Comment by mitalcoi** [comment]
у меня сервер на debian, локально стоит ubuntu, кодировка везде и повсюду одна - utf-8

**Comment by romankazakov** [comment]
0)Из строки уберите лидирующие и конечные пробелы.
1)Подпись вычислять по строке в windows-1251.

**Comment by kotchuprik** [comment]
Я думаю, что проблема уже решена. Если вопрос не поднимался

**Comment by romankazakov** [comment]
У меня возникла такая же проблема, на известном тебе сайте. Здесь я решения не нашёл.

**Comment by kotchuprik** [comment]
@romankazakov уже решил надеюсь?) Если нет, писани в скайп, попробую помочь :)

**Comment by romankazakov** [comment]
Костя, я решение выше описал.

**Comment by kotchuprik** [comment]
А, ну ок. По идее, строка и не должна быть с пробелами вначале и в конце, вебмани это не любит. Ровно как и любит вин1251. Это очень важные моменты
