### ISSUE TITLE
реализация сертификата Webmoney

### ISSUE THREAD

**Issue by mitalcoi** [baibaratsky/php-webmoney#67]
WMXI позволяет использовать сертификат Webmoney для защиты от атаки с подменой DNS. Реализуется очень просто - в корень ложиться сертификат (в WMXI документ называется WebMoneyCA.crt) и затем в CurlRequester добавляется несколько параметров в запрос:
```php
curl_setopt($ch, CURLOPT_CAINFO, __DIR__.'/WebMoneyCA.crt');
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
```
Что думаете насчет реализации такого улучшения и в php-webmoney?

**Comment by baibaratsky** [comment]
Я это решение не использовал, т. к. у WM были проблемы с актуальностью этого сертификата.
Если эта фича вам нужна, готов подумать о том, как лучше ее прицепить, чтобы не создать новых проблем, тоже после 23-го (или если вдруг время раньше появится).
