### ISSUE TITLE
Интерфейс X2, trans\wminvid 

### ISSUE THREAD

**Issue by paurlift** [baibaratsky/php-webmoney#86]
Здравствуйте, подскажите, пожалуйста, где взять значение trans\wminvid  ? 

В описание интерфейса сказано следующее - trans\wminvid	- это номер счета (в системе WebMoney), по которому выполняется перевод, целое число > 0; если 0 - перевод не по счету. 

Устанавливается он функцией $request->setInvoiceId(0); 
Если указывать wminvid	 равным 0, то перевод как будто происходит, в ответ приход код ответа - 0 и id транзакции, но на самом деле деньги не списываются с кошелька и не поступают на другой кошелек. 

Спасибо.

**Comment by baibaratsky** [comment]
Очевидно, проблема в чем-то другом. Если wminvid=0, платежи отлично проходят.

**Comment by roman-rybalko** [comment]
У вас возможно включен тестовый режим в merchant.

**Comment by paurlift** [comment]
Спасибо за помощь и вправду все работает с 0. Списание и поступление почему-то не сразу отобразились.
