### ISSUE TITLE
Uncaught exception 'Exception' with message 'Hash check failed. Key file seems to be corrupted.'

### ISSUE THREAD

**Issue by hitman2599** [baibaratsky/php-webmoney#88]
Hello.

I get this error :

root@s15:/home/wmz3# php test1.php
PHP Fatal error:  Uncaught exception 'Exception' with message 'Hash check failed. Key file seems to be corrupted.' in /home/wmz3/vendor/baibaratsky/php-wmsigner/Signer.php:53
Stack trace:
#0 /home/wmz3/test1.php(14): baibaratsky\WebMoney\Signer->__construct('XXXX10261095', 'XXXX10261095.kw...', 'Password1234!@#...')
#1 {main}
  thrown in /home/wmz3/vendor/baibaratsky/php-wmsigner/Signer.php on line 53
root@s15:/home/wmz3#

On this script : 
https://github.com/baibaratsky/php-webmoney/wiki/X3

I have double check the WMID and PASS ... with those crededentials i enter my account.

The KVM file was creeated from my computer and i am trying to use the key from my server (Ubuntu 14.04.2 LTS). What i am doing wrong? Please help me.

Thanks.

**Comment by baibaratsky** [comment]
If I got it right, you use your account password instead of the key password. Is it true?

**Comment by hitman2599** [comment]
Thank you for the answer. There are two different things??? i didn't even know ... aren't they the same? and if no, where i could get this KEY PASSWORD ??

**Comment by baibaratsky** [comment]
You input it when generating a key. If you can’t recall it, just create a new key.

**Comment by hitman2599** [comment]
So i must create a new key with WINPRO (http://www.webmoney.ru/rus/information/manage/winpro.shtml) or i must submit a request to webmoney?

**Comment by baibaratsky** [comment]
Use WinPro.

**Comment by hitman2599** [comment]
I have double check with my team, the KVM password is the same as the ACCOUNT password, i have seen with my eyes when i try to log with WINPRO. Why gives me that error?

The ideea is that the KVM  key was generated on PC1 (windows) and i am trying to make an API for our SERVER1 (linux).

Do i do something wrong?

Thanks.

**Comment by baibaratsky** [comment]
There is no problem to use on a Linux system a key generated on Windows.
Did you try to create a new key?
