### ISSUE TITLE
X2 - ошибка валидации onlyauth

### ISSUE THREAD

**Issue by rolmonk** [baibaratsky/php-webmoney#92]
В интерфейсе X2 в запросе при присвоении onlyauth принудительно приводится к `(bool)`, а поскольку для X2 он обязателен - `validateRequired` проверяет его на `is_numeric()`, что приводит к ошибке валидации в любом случае. Поскольку в доках вебманей возможные значения указаны как `0` и `1`, думаю, проще всего приводить его к `(int)`

**Comment by baibaratsky** [comment]
@rolmonk проверьте, пожалуйста, мой вариант. Все-таки я думаю, лучше работать с bool и правильно его валидировать.

**Comment by rolmonk** [comment]
Да, так тоже работает, спасибо!
