### ISSUE TITLE
Create new validation rule when one parameter is non mandatory if other is specified

### ISSUE THREAD

**Issue by vitalijssilins** [baibaratsky/php-webmoney#97]
There is need of validation rule, when one parameter becomes non-mandatory if other parameter is specified.

Example: 
payment/purse and payment/phone parameters in WMC1 interface:
https://wiki.webmoney.ru/projects/webmoney/wiki/%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81_WMC1

**Comment by baibaratsky** [comment]
@kotchuprik Validators is your area, so do anything please ;)

**Comment by kotchuprik** [comment]
I think we can try to use TYPE_DEPEND_REQUIRED rule. @vitalijssilins could you try something like this?

```php
protected function getValidationRules()
{
  return array(
    RequestValidator::TYPE_DEPEND_REQUIRED => array(
          'purse' => array('phone' => array('')),
          'phone' => array('purse' => array('')),
    ),
  );
}
```

I'm sure that this looks not fine but I'm not sure that we need to do yet validation rule if this will be working.

Example for using depend required rule [here](https://github.com/baibaratsky/php-webmoney/blob/b33950b8694ce4f56d1c06a77d4962231ec86912/Api/MegaStock/AddMerchant/Request.php#L78).
