### ISSUE TITLE
Исправить проблемы с приведением типа

### ISSUE THREAD

**Issue by stas17** [baibaratsky/php-webmoney#98]
Привет, нашел ошибку. в baibaratsky\WebMoney\Api\X\X22\Request

    /**
     * @param string $payeePurse lmi_payee_purse
     */
    public function setPayeePurse($payeePurse)
    {
        $this->payeePurse = (int)$payeePurse;
    }

соответственно надо (int) на (string)

    /**
     * @param string $payeePurse lmi_payee_purse
     */
    public function setPayeePurse($payeePurse)
    {
        $this->payeePurse = (string)$payeePurse;
    }

За либу гранд мерси!!!

**Comment by baibaratsky** [comment]
Спасибо за репорт!
