### ISSUE TITLE
Накатить версию))

### ISSUE THREAD

**Issue by stas17** [baibaratsky/php-webmoney#99]
Изменения внесенные 2 августа не добавлены в версию, можно плз накатить новую.

Еще раз спасибо за либу

**Comment by baibaratsky** [comment]
Скоро будет. Сейчас еще один апдейт приготовим.

**Comment by baibaratsky** [comment]
Enjoy!
https://github.com/baibaratsky/php-webmoney/releases/tag/v0.15.0
